project:
  type: book

book:
  title: "Introduction to programming and scientific computing"
  author: "Ven Popov"
  date: "2/23/2025"
  search: true
  repo-url: "https://github.com/venpopov/programming-intro-book"
  repo-actions: [edit, issue]
  repo-branch: "main"
  favicon: images/cover.png
  issue-url: "https://github.com/venpopov/programming-intro-book/issues"
  chapters:
    - index.qmd
    - preface.qmd
    - introduction.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand



